spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productcategory
    username: root
    password: Bhuvi@1399
  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081